# These are supported funding model platforms
# github: [your-github-username]
# open_collective: [your-collective]
# patreon: [your-patreon]
# ko_fi: [your-kofi]
# custom: ['https://buymeacoffee.com/yourname']
